server:
  port: 8082

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/payment?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    stream:
      kafka:
        binder:
          autoCreateTopics: true
          brokers: localhost:9092
          configuration:
            value:
              deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
              serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            key:
              deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
              serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      bindings:
        checkout-created-input:
          destination: streaming.ecommerce.checkout.created
          contentType: application/*+avro
          group: payment
          consumer:
            use-native-decoding: true
        payment-paid-output:
          destination: streaming.ecommerce.payment.paid
          contentType: application/*+avro
          producer:
            use-native-encoding: true
    kafka:
      properties:
        schema:
          registry:
            url: http://localhost:8081
    application:
      name: payment-api

